name: pi-gen-action
description: Build a custom Raspberry Pi image using pi-gen
author: Simon Domke

inputs:
  # pi-gen variables

  image-name:
    description: Final image name.
    required: true
  use-qcow2:
    description: Use qcow2 images to reduce space and runtime requirements.
    required: false
    default: 1
  setfcap:
    description: |
      Setting to `1` will prevent pi-gen from dropping the "capabilities" feature. Generating the root filesystem with capabilities enabled and running
      it from a filesystem that does not support capabilities (like NFS) can cause issues. Only enable this if you understand what it is.
    required: false
    default: ''
  stage-list:
    description: |
      List of stage name to execute in given order. Relative and absolute paths to custom stage directories are allowed here.
      Note that by default pi-gen exports images in stage2 (lite), stage4 and stage5. You probably want to hook in custom stages
      before one of the exported stages. Otherwise, the action will make sure any custom stage will include an image export directive.
    required: false
    default: 'stage0 stage1 stage2'
  release:
    description: The release version to build images against. Valid values are bullseye, buster, stretch, jessie, and wheezy.
    required: false
    default: bullseye
  compression:
    description: Compression to apply on final image (either "none", "zip", "xz" or "gz").
    required: false
    default: zip
  compression-level:
    description: Compression level to be used. From 0 to 9 (refer to the tool man page for more information on this. Usually 0 is no compression but very fast, up to 9 with the best compression but very slow).
    required: false
    default: 6
  locale:
    description: Default locale of the system image.
    required: false
    default: en_GB.UTF-8
  hostname:
    description: Host name of the image.
    required: false
    default: raspberrypi
  keyboard-keymap:
    description: Default keyboard keymap.
    required: false
    default: gb
  keyboard-layout:
    description: Default keyboard layout.
    required: false
    default: English (UK)
  timezone:
    description: System timezone.
    required: false
    default: Europe/London
  username:
    description: Name of the initial user account.
    required: false
    default: pi
  password:
    description: Password of the intial user account, locked if empty.
    required: false
  disable-first-boot-user-rename:
    description: |
      Disable the renaming of the first user during the first boot. This make it so 'username' stays activated. 
      'username' must be set for this to work. Please be aware of the implied security risk of defining a default 
      username and password for your devices.
    required: false
    default: 0
  wpa-essid:
    description: SSID of a default wifi network to connect to.
    required: false
  wpa-password:
    description: Password of default wifi network to connect to.
    required: false
  wpa-country:
    description: Wifi country code of default network to connect to.
    required: false
  enable-ssh:
    description: Enable SSH access to Pi.
    required: false
    default: 0
  docker-opts:
    description: Additional options to include in PIGEN_DOCKER_OPTS
    required: false
    default: ""

  # action variables

  pi-gen-repository:
    description: GitHub repository to fetch pi-gen from, must be a fork from RPi-Distro/pi-gen.
    required: false
    default: RPi-Distro/pi-gen
  export-last-stage-only:
    description: |
      If this feature is enabled, the action will configure pi-gen to not export any stage as image but the last one
      defined in property 'stage-list'. This is helpful when building a single image flavor (in contrast to building
      a lite/server and full-blown desktop image), since it speeds up the build process significantly.
    required: false
    default: true
  pi-gen-version:
    description: Release version of pi-gen to use. This can both be a branch or tag name known in the pi-gen repository.
    required: false
    # Currently, theres a bug in pi-gen if building for 64bit targets: https://github.com/RPi-Distro/pi-gen/issues/271
    # We assume this is mostly the case, so this is set to the fix in the branch by default
    default: arm64
  enable-noobs:
    description: Set whether a NOOBS image should be built as well. If enabled, the output directory containing the NOOBS files will be saved as output variable 'image-noobs-path'.
    required: false
    default: false
  extra-host-dependencies:
    description: |
      Comma or whitespace separated list of additional packages to install on host before running pi-gen.
      Use this list to add any packages your custom stages may require. Note that this is not affecting the final image. In order to add additional packages, you need to add a respective 'XX-packages' file in your custom stage.
    required: false
    default: ''
  extra-host-modules:
    description: |
      Comma or whitespace separated list of additional modules to load on host before running pi-gen.
      If your custom stage requires additional software or kernel modules to be loaded, add them here. Note that this is not meant to configure modules to be loaded in the target image.
    required: false
    default: ''
  pi-gen-dir:
    description: Path where selected pi-gen ref will be checked out to. If the path does not yet exist, it will be created (including its parents).
    required: false
    default: pi-gen
  verbose-output:
    description: Print all output from pi-gen.
    required: false
    default: false
  github-token:
    description: Token to use for checking out pi-gen repo.
    required: false
    default: ${{ github.token }}

outputs:
  image-path:
    description: Path to the final custom image
  image-noobs-path:
    description: Path to final noobs image, if enabled

runs:
  using: node16
  main: dist/index.js
  post: dist/index.js

branding:
  icon: box
  color: red
