name: pi-gen-action-integration-test
on:
  workflow_dispatch:
  push:

env:
  MOUNT_DIR: /mnt
  ROOTFS_DIR: /mnt/root

jobs:

  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run pi-gen build
        uses: ./
        id: build
        with:
          image-name: integration-test
          stage-list: stage0 stage1 ./__test__/it-test-stage
          verbose-output: true
          enable-noobs: true
          compression: xz
          compression-level: 9
          locale: de_DE.UTF-8
          hostname: pi-gen-test
          keyboard-keymap: de
          keyboard-layout: German - no dead keys
          username: pi-gen
          wpa-essid: foo
          wpa-password: '1234567890'
          timezone: Europe/Berlin

      - name: List working directory
        run: tree 
      
      - name: Uncompress image and mount loopback device
        run: |
          set -ex
          xz -d ${{ steps.build.outputs.image-path }}
          file_name="${{ steps.build.outputs.image-path }}"
          ./__test__/mount-pi-gen-image.sh "${file_name/.xz/}" $MOUNT_DIR
      
      - name: Test configuration values
        run: |
          set -ex
          test -x ${ROOTFS_DIR}/usr/bin/node
          test "$(cat ${ROOTFS_DIR}/etc/hostname)" = "pi-gen-test"
          grep pi-gen ${ROOTFS_DIR}/etc/passwd
          source ${ROOTFS_DIR}/etc/default/locale
          test "$LANG" = "de_DE.UTF-8"
          test "$(cat ${ROOTFS_DIR}/etc/timezone)" = "Europe/Berlin"

          