name: Publish release

on:
  release:
    types: 
      - released
      - edited

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0 # fetch full history for Git tests

      - uses: actions/setup-node@v4
        with:
            node-version: 20
            cache: npm

      - name: Test and create dist files
        run: npm ci && npm run all

      - name: Push dist to new tag
        uses: teunmooij/github-versioned-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          include: |-
            dist/licenses.txt
            dist/index.js
            README.md
            LICENSE
            action.yml

      - name: Set release to published
        uses: irongut/EditRelease@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          id: ${{ github.event.release.id }}
          draft: false
          prerelease: false