name: Publish release

on:
  release:
    types: 
      - released

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0 # fetch full history for Git tests

      - uses: actions/setup-node@v4
        with:
            node-version: 20
            cache: npm

      - name: Test and create dist files
        run: npm ci && npm run all

      - name: Push dist to new tag
        uses: teunmooij/github-versioned-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          include: |-
            dist/licenses.txt
            dist/index.js
            README.md
            LICENSE
            action.yml