name: Create GH release on version change
on:
  push: 
    branches: 
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check if package.json version changed
        uses: EndBug/version-check@v2
        id: check

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: steps.check.outputs.changed == 'true'
        with:
          tag_name: v${{ steps.check.outputs.version }}
          generate_release_notes: true
          prerelease: true
          draft: false
